### ISSUE TITLE
FontCollection.SystemFonts.DefaultFont if it is null

### ISSUE THREAD

**Issue by vahpetr** [activereports/WebSamples15#1]
Reproduce:
1/ Create `docker-compose.yml` file
2/ `docker-compose up -d`
3/ `open localhost:80`
4/ open any report, `Tablix.rdlx` for example
5/ run `Preview`

Result:
Failed rendering document.
TextFormat has no associated Font, and a default font could not be found. To avoid this situation, assign an available font to FontCollection.SystemFonts.DefaultFont if it is null.

Expectation:
No error. Correct preview.

Docker image for reproduce this bug [https://hub.docker.com/repository/docker/vahpetr/webdesigner-mvc-core](url)
`docker pull vahpetr/webdesigner-mvc-core:1.0.0`

Docker-compose
```
version: "3.9"

services:
  reports:
    image: vahpetr/webdesigner-mvc-core:1.0.0
    restart: always
    volumes:
      - reports_resources:/app/resources
      - reports_datasets:/app/datasets
      - reports_templates:/app/templates
    ports:
      - 80:80
      - 443:443

volumes:
  reports_resources:
    driver: local
  reports_datasets:
    driver: local
  reports_templates:
    driver: local
```

I think problem in miss default fonts in container.

P.S The container is created automatically by the dotnet tool tye [https://github.com/dotnet/tye](url)
